package co.sistemcobro.yanbal.constante;


public enum ParametrosSistemaEnum {
	RUTAL_TEMPORAL_SISTEMCARTERA,
	ID_APLICACION_SISTEMCARTERA,
	WS_LOGIN_SISTEMCARTERA,
	WS_LOGIN_JSON_USER,
	WS_LOGIN_JSON_PWD,
	WS_LOGIN_JSON_APP,
	WS_LOGIN_BASIC_AUTENTICACION_USER,
	WS_LOGIN_BASIC_AUTENTICACION_PASS,
	SEPARADOR_ARCHIVO_DEUDORES,
	TAMAÑO_REGISTROS_BATCH,
	FORMATO_FECHA_HORA,
	FORMATO_FECHA,
	SEPARADOR_ARCHIVOS_VALIDACION,
	NOMBRE_ARCHIVO_RESULTADO_VALIDACION_ESTRUCTURA_DEUDORES,
	EXTENSION_ARCHIVOS_VALIDACION,
	FORMATO_FECHA_SIN_SEPARADOR;
}


